@startuml Components
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

System_Boundary(interviewSystem, "Система онлайн-собеседований") {

    Container(spa, "Веб-приложение", "React", "Пользовательский интерфейс")
    
    Boundary(interviewTrainerApi, "API Backend") {
    
        Component(api, "API", "ASP.NET Core")
        
        Component(usersModule, "Модуль пользователей", ".NET Libraries")
        Component(questionBankModule, "Модуль банка задач", ".NET Libraries")
        Component(interviewModule, "Модуль собеседований", ".NET Libraries")
        Component(codeRunnerModule, "Модуль выполнения кода", ".NET Libraries")
        
        ComponentQueue(eventsBus, "Events Bus", "In memory")
        
        Boundary(database, "База данных") {
            ComponentDb(usersModuleData, "Данные пользователей", "schema")
            ComponentDb(questionBankModuleData, "Данные банка задач", "schema")
            ComponentDb(interviewModuleData, "Данные собеседований", "schema")
            ComponentDb(codeRunnerModuleData, "Данные выполнения кода", "schema")
        }
    }
}

System_Ext(keycloak, "Keycloak", "Сервис авторизации и аутентификации")
System_Ext(aiAPI, "AI API", "Внешнее API для генерации обратной связи")

Rel(spa, api, "Выполняет запросы через API", "HTTP")
Rel(api, usersModule, "Вызывает функции управления пользователями")
Rel(api, questionBankModule, "Вызывает функции работы с банком вопросов")
Rel(api, interviewModule, "Управляет сессиями собеседований")
Rel(api, codeRunnerModule, "Отправляет код на выполнение")
Rel(usersModule, usersModuleData, "Чтение/запись данных")
Rel(questionBankModule, questionBankModuleData, "Чтение/запись данных")
Rel(interviewModule, interviewModuleData, "Чтение/запись данных")
Rel(codeRunnerModule, codeRunnerModuleData, "Чтение/запись данных")

Rel(usersModule, eventsBus, "Публикует/подписывается на события")
Rel(questionBankModule, eventsBus, "Публикует/подписывается на события")
Rel(interviewModule, eventsBus, "Публикует/подписывается на события")
Rel(codeRunnerModule, eventsBus, "Публикует/подписывается на события")

Rel(usersModule, keycloak, "Использует для аутентификации пользователей", "HTTP")
Rel(interviewModule, aiAPI, "Запрашивает оценку и обратную связь по ответам кандидата", "HTTP")

LAYOUT_WITH_LEGEND()
@enduml
